[package]
name = "wordglow"
version.workspace = true
edition.workspace = true

[[bin]]
name = "wordglow"
path = "src/main.rs"

[dependencies]
serde = { workspace = true, features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wordglow_core = { package = "wordglow-core", path = "../core" }
rusqlite.workspace = true
tauri = { version = "2.11.5", features = [] }
base64.workspace = true
dotenvy.workspace = true
envy.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
leptos = { version = "0.8.20", features = ["csr"] }
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.78"
js-sys = "0.3.105"
base64.workspace = true
web-sys = { version = "0.3.105", features = ["console", "HtmlAudioElement", "HtmlMediaElement", "HtmlInputElement", "Window", "File", "FileList", "FileReader", "Event"] }

[build-dependencies]
tauri-build = "2.6.3"
